version: '3.6'
services:
  mongodb:
    image: mongo:5.0.2
    container_name: mongodb
    restart: unless-stopped
    env_file: ./.env
    ports:
      - '27017:27017'
    volumes:
      - db:/data/db

  nats:
    image: nats:latest
    container_name: nats
    restart: unless-stopped
    ports:
      - '4222:4222'
      - '6222:6222'
      - '8222:8222'

  server:
    container_name: nestjs
    depends_on:
      - mongodb
      - nats
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=$MONGODB_PORT
      - MONGODB_DATABASE=$MONGODB_DATABASE
      - CURRENCY_FREAKS_TOKEN=$CURRENCY_FREAKS_TOKEN
      - CURRENCY_FREAKS_URL=$CURRENCY_FREAKS_URL
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src/
    command: npm run start:prod

volumes:
  db:
